### ISSUE TITLE
Fport rssi scale

### ISSUE THREAD

**Issue by VadimGromov** [iNavFlight/inav#3497]
INAV/OMNIBUS 2.0.0 Jun 29 2018 / 12:33:58 (a8415e89c)

R9mini connected via fport. The rssi max value is 50% and does not changes with rssi_scale.

**Comment by shellixyz** [comment]
Please give us more details:
- Config diff/dump
- How is the RSSI sent ? SBus channel ? Which one ?

**Comment by VadimGromov** [comment]
RSSI sent via fport. ADC and channel are disabled.

[diff.txt](https://github.com/iNavFlight/inav/files/2160124/diff.txt)

**Comment by Droneracer101** [comment]
I am having the same issue with iNAV 1.9.1.  F.Port natively transmits RSSI, not analog, not on a channel. I have confirmed it works, but rssi_scale isn't working with it.  It shows 50% of the true value.  It does the exact same thing in Betaflight 3.4 but there I can use set rssi_scale =200 and then it scales perfectly with the RSSI displayed on the radio.  Doing the same thing in iNav doesn't seem to affect the displayed value with this input.  

This is what set rssi? shows me:
# set rssi
rssi_adc_channel = 0
Allowed range: 0 - 4

rssi_channel = 0
Allowed range: 0 - 18

rssi_scale = 200
Allowed range: 1 - 255

rssi_invert = OFF
Allowed values: OFF, ON

osd_rssi_alarm = 60
Allowed range: 0 - 100

osd_rssi_pos = 2071
Allowed range: 0 - 3071


For reference is here the same value I am using in Betaflight with F.Port.  The only difference is the rssi_scale seems to work.

# set rssi
rssi_channel = 0
Allowed range: 0 - 18

rssi_src_frame_errors = OFF
Allowed values: OFF, ON

rssi_scale = 200
Allowed range: 1 - 255
Default value: 100

rssi_offset = 0
Allowed range: -100 - 100

rssi_invert = OFF
Allowed values: OFF, ON

osd_rssi_alarm = 20
Allowed range: 0 - 100

osd_rssi_pos = 2284
Allowed range: 0 - 3071
Default value: 234

osd_stat_min_rssi = ON
Allowed values: OFF, ON

Also, rssi_scale does seem to work in iNAV if I have another rssi method selected. Just not with F.Port.  But now that I have it I really like FPort RSSI.  It seems to most accurately match the value on my radio.

**Comment by fiam** [comment]
Fixed in #3613

**Comment by MrVinther** [comment]
Can confirm that this issue is still present in 2.0.0 final
Using Matek f722 board Frsky R9 mini using latest F-port non-EU firmware.

**Comment by teckel12** [comment]
@MrVinther Are you setting the new `rssi_min` and `rssi_max` values?

**Comment by MrVinther** [comment]
This results in 50% rssi in the configurator. I have 100% rssi on my Horus.
The old rssi_scale could be set to 200 which solved the problem.


rssi_adc_channel = 3
Allowed range: 0 - 4

rssi_channel = 0
Allowed range: 0 - 18

rssi_min = 0
Allowed range: 0 - 100

rssi_max = 100
Allowed range: 0 - 100

osd_rssi_alarm = 20
Allowed range: 0 - 100

**Comment by MrVinther** [comment]
Im sorry for this. I understand now how to set the rssi_max value. Setting it to 50% as the max showed value in the configurator gives me 100%.

**Comment by teckel12** [comment]
@MrVinther Yeah, no need for scale.  You simply set the min and max values to what they are (even if the max value is negative) and the code will take care of the rest.

**Comment by jasc76** [comment]
Just as info:
Using:
Matek F405 Wing
Inav 2.0
R9 MM F.Port (Firmware FW-R9MINI-R9MM-F.PORT-180629)

I had to set rssi_channel = 0 and rssi_adc = 0 otherwise fport rssi would not show correctly. rssi_adc was set I think to 2 in the defaults.
thought I should share that

**Comment by throttlenerd** [comment]
Same here, guys! Matek F722SE, R9MM. Flashed EmuFlight just to check the rssi_scale method -- works perfectly. Flashed iNav 2.3.0 RC2 (configurator is updated too) -- no, only rssi_min and rssi_max which is already maxed out at 100. But my R9MM is flashed with FLEX firmware and it outputs RSSI on channel 16, so I will just use it as an rssi_source.

**Comment by agrestic1** [comment]
Same here! Matek F722SE, R9MM with FLEX firmware on iNAV 2.5.0 RC1
But using Channel 16 works fine!

**Comment by skorokithakis** [comment]
For anyone looking at this thread for a solution, it looks like to solve this you can EITHER do:

```
set rssi_max = 50
```

OR, if your receiver sends RSSI back on channel 16:

```
set rssi_channel = 16
```
